"""empty message

Revision ID: 399d044003c9
Revises: 3a6ebba0f694
Create Date: 2014-03-31 18:58:50.164064

"""

# revision identifiers, used by Alembic.
revision = '399d044003c9'
down_revision = '3a6ebba0f694'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount_rate', sa.Float(), nullable=True))
    op.add_column('set', sa.Column('big_img_url', sa.String(length=255), nullable=True))
    op.add_column('set', sa.Column('discount_rate', sa.Float(), nullable=True))
    op.add_column('set', sa.Column('small_img_url', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('set', 'small_img_url')
    op.drop_column('set', 'discount_rate')
    op.drop_column('set', 'big_img_url')
    op.drop_column('product', 'discount_rate')
    ### end Alembic commands ###
