"""empty message

Revision ID: 3a6ebba0f694
Revises: None
Create Date: 2014-03-29 11:51:11.974752

"""

# revision identifiers, used by Alembic.
revision = '3a6ebba0f694'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('user_key', sa.Integer(), nullable=True),
    sa.Column('product_key', sa.Integer(), nullable=True),
    sa.Column('set_key', sa.Integer(), nullable=True),
    sa.Column('is_set', sa.Boolean(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_key'], ['product.key'], ),
    sa.ForeignKeyConstraint(['set_key'], ['set.key'], ),
    sa.ForeignKeyConstraint(['user_key'], ['users.key'], ),
    sa.PrimaryKeyConstraint('key'),
    sa.UniqueConstraint('user_key', 'product_key')
    )
    op.drop_table(u'migrate_version')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'migrate_version',
    sa.Column(u'repository_id', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column(u'repository_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column(u'version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'repository_id', name=u'migrate_version_pkey')
    )
    op.drop_table('interest')
    ### end Alembic commands ###
