"""empty message

Revision ID: 4819228fefcc
Revises: b3f4825b84b
Create Date: 2014-04-05 13:44:37.988209

"""

# revision identifiers, used by Alembic.
revision = '4819228fefcc'
down_revision = 'b3f4825b84b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'created_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'created_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    ### end Alembic commands ###
