"""empty message

Revision ID: b3f4825b84b
Revises: 42543d4383a3
Create Date: 2014-04-05 13:37:12.735258

"""

# revision identifiers, used by Alembic.
revision = 'b3f4825b84b'
down_revision = '42543d4383a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    ### end Alembic commands ###
